import{a as P,S as q,i as n}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const v="https://pixabay.com/api/",M="54229947-cd8105fd48042137517a5f764";async function p(r,t){return(await P.get(v,{params:{page:t,per_page:15,key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),u=document.querySelector(".btn-load-more"),B=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const t=r.map(({webformatURL:i,largeImageURL:l,tags:e,likes:o,views:a,comments:S,downloads:b})=>`<li class="gallery-item">
            <a href="${l}"
              ><img src="${i}" alt="${e}" loading="lazy"
            /></a>
            <ul class="description">
              <li><p><span class="title-info">Likes</span>${o}</p></li>
              <li><p><span class="title-info">Views</span>${a}</p></li>
              <li><p><span class="title-info">Comments</span>${S}</p></li>
              <li><p><span class="title-info">Downloads</span>${b}</p></li>
            </ul>
          </li>`).join("");f.insertAdjacentHTML("beforeend",t),B.refresh()}function R(){f.innerHTML=""}function h(){m.classList.remove("hidden")}function y(){m.classList.add("hidden")}function L(){u.classList.remove("hidden")}function w(){u.classList.add("hidden")}const $=document.querySelector(".form");let d=0,c="",s=1;$.addEventListener("submit",O);u.addEventListener("click",x);async function O(r){if(r.preventDefault(),c=r.target.elements["search-text"].value.trim(),c===""){n.error({message:"Please fill in the search field",position:"topRight"});return}s=1,R(),w(),h();try{const t=await p(c,s),i=t.hits;if(i.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(i),d=Math.ceil(t.totalHits/15),s<d&&L()}catch{n.error({message:"Something went wrong. Please try again later",position:"topRight"})}finally{y()}}async function x(){s+=1,w(),h();try{const t=(await p(c,s)).hits;g(t),E(),s<d?L():n.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch{n.error({message:"Something went wrong. Please try again later",position:"topRight"})}finally{y()}}function E(){const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
